# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='Publico',
            field=models.NullBooleanField(verbose_name=b'P\xc3\xbablico'),
        ),
    ]
