# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estabelecimento_Desempenha_Atv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Manipular', models.BooleanField()),
                ('Fracionar', models.BooleanField()),
                ('Dispensar', models.BooleanField()),
                ('AferirParam', models.BooleanField(verbose_name=b'Aferir par\xc3\xa2metros fisiol\xc3\xb3gicos e bioqu\xc3\xadmico')),
                ('PrestarAten', models.BooleanField(verbose_name=b'Prestar aten\xc3\xa7\xc3\xa3o farmac\xc3\xaautica domiciliar')),
                ('AdmAplicar', models.BooleanField(verbose_name=b'Administrar/aplicar medicamentos')),
                ('Perfurar', models.BooleanField(verbose_name=b'Perfurar l\xc3\xb3bulo auricular para coloca\xc3\xa7\xc3\xa3o de brinco')),
                ('DispRemoto', models.BooleanField(verbose_name=b'Dispensar por meio remoto')),
                ('Fabricar', models.BooleanField()),
                ('Transformar', models.BooleanField()),
                ('Purificar', models.BooleanField()),
                ('Extrair', models.BooleanField()),
                ('Fragmentar', models.BooleanField()),
                ('Sintetizar', models.BooleanField()),
                ('EstRadiacaoIon', models.BooleanField(verbose_name=b'Esterelizar radia\xc3\xa7\xc3\xa3o ionizante')),
                ('EstETO', models.BooleanField(verbose_name=b'Esterelizar ETO')),
                ('EstOutras', models.BooleanField(verbose_name=b'Esterelizar outras')),
                ('Reprocessar', models.BooleanField()),
                ('Irradiar', models.BooleanField()),
                ('Transportar', models.BooleanField()),
                ('Expedir', models.BooleanField()),
                ('Armazenar', models.BooleanField()),
                ('Embalar', models.BooleanField()),
                ('Distribuir', models.BooleanField()),
                ('Importar', models.BooleanField()),
                ('ImpUsoProprio', models.BooleanField(verbose_name=b'Importar para uso pr\xc3\xb3prio')),
                ('Exportar', models.BooleanField()),
                ('RealEtapFab', models.BooleanField(verbose_name=b'Realizar etapas de fabrica\xc3\xa7\xc3\xa3o')),
                ('Atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segCadastro.Atividade', verbose_name=b'Atividade(s) Econ\xc3\xb4mica(s)')),
                ('Estabelecimento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segCadastro.Estabelecimento', verbose_name=b'Estabelecimento')),
                ('ResponsavelTecnico', models.ManyToManyField(blank=True, to='segCadastro.Responsavel', verbose_name=b'Respons\xc3\xa1vel(eis) T\xc3\xa9cnico(s)')),
                ('Setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segCadastro.Setor')),
                ('Veiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='segCadastro.Veiculo')),
            ],
            options={
                'verbose_name': 'Caracteriza\xe7\xe3o da Atividade Econ\xf4mica',
                'verbose_name_plural': 'Caracteriza\xe7\xf5es das Atividades Econ\xf4micas',
            },
        ),
        migrations.RemoveField(
            model_name='fisica_desempenha_atv',
            name='Atividade',
        ),
        migrations.RemoveField(
            model_name='fisica_desempenha_atv',
            name='PessoaFisica',
        ),
        migrations.RemoveField(
            model_name='fisica_desempenha_atv',
            name='Setor',
        ),
        migrations.RemoveField(
            model_name='juridica_desempenha_atv',
            name='Atividade',
        ),
        migrations.RemoveField(
            model_name='juridica_desempenha_atv',
            name='PessoaJuridica',
        ),
        migrations.RemoveField(
            model_name='juridica_desempenha_atv',
            name='ResponsavelTecnico',
        ),
        migrations.RemoveField(
            model_name='juridica_desempenha_atv',
            name='Setor',
        ),
        migrations.RemoveField(
            model_name='juridica_desempenha_atv',
            name='Veiculo',
        ),
        migrations.RemoveField(
            model_name='pessoa_fisica',
            name='Atividade',
        ),
        migrations.RemoveField(
            model_name='pessoa_juridica',
            name='Atividade',
        ),
        migrations.DeleteModel(
            name='Fisica_Desempenha_Atv',
        ),
        migrations.DeleteModel(
            name='Juridica_Desempenha_Atv',
        ),
        migrations.AddField(
            model_name='estabelecimento',
            name='Atividade',
            field=models.ManyToManyField(through='segCadastro.Estabelecimento_Desempenha_Atv', to='segCadastro.Atividade'),
        ),
        migrations.AddField(
            model_name='processo',
            name='Estab_atividade',
            field=models.ManyToManyField(blank=True, to='segCadastro.Estabelecimento_Desempenha_Atv'),
        ),
    ]
