# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-28 07:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0002_documento_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Publico',
            field=models.BooleanField(verbose_name=b'P\xc3\xbablico'),
        ),
    ]
