# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 03:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0002_auto_20160216_2325'),
    ]

    operations = [
        migrations.RenameField(
            model_name='processo',
            old_name='Estab_atividade',
            new_name='Estab_Atividade',
        ),
    ]
