# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-17 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0003_auto_20160217_0006'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processo',
            name='Estab_Atividade',
        ),
        migrations.AddField(
            model_name='processo',
            name='Atividade_Estabelecimento',
            field=models.ManyToManyField(blank=True, related_name='atividades_estab', to='segCadastro.Estabelecimento_Desempenha_Atv'),
        ),
    ]
