# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 01:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0004_auto_20160217_0111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processo',
            name='Atividade_Estabelecimento',
            field=models.ManyToManyField(blank=True, related_name='atividades_estab', to='segCadastro.Estabelecimento_Desempenha_Atv', verbose_name=b'Atividade ou Atividade/Ve\xc3\xadculo'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='ProcessoMae',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='segCadastro.Processo', verbose_name=b'Processo M\xc3\xa3e'),
        ),
    ]
