# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 23:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0003_auto_20160328_0402'),
        ('segCadastro', '0004_auto_20160328_0611'),
    ]

    operations = [
    ]
