# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 17:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0005_auto_20160218_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipamento_saude',
            name='Caracteristicas',
            field=models.TextField(null=True, verbose_name=b'Caracter\xc3\xadsticas'),
        ),
        migrations.AlterField(
            model_name='equipamento_saude',
            name='Tipo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='segCadastro.Tipo_Equipamento_Saude'),
        ),
    ]
