# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0005_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estabelecimento_desempenha_atv',
            name='Setor',
        ),
        migrations.AddField(
            model_name='processo',
            name='Setor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='segCadastro.Setor'),
        ),
        migrations.AlterField(
            model_name='processo',
            name='TramitaSetor',
            field=models.ManyToManyField(blank=True, related_name='tramita_setor', through='segCadastro.Processo_Tramita_Setor', to='segCadastro.Setor'),
        ),
    ]
