# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-21 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0007_auto_20160221_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autorizacao_funcionamento',
            name='PessoaJuridica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='segCadastro.Pessoa_Juridica'),
        ),
    ]
