# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-01 09:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0008_auto_20160401_0458'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['DataHora'], 'permissions': (('emitir_alvara', 'Pode emitir Alvar\xe1'),)},
        ),
    ]
