# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-13 17:00
from __future__ import unicode_literals

from django.db import migrations, models
import segCadastro.models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0009_auto_20160401_0614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Arquivo',
            field=models.FileField(blank=True, max_length=500, upload_to=segCadastro.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name='pessoa_juridica',
            name='ResponsaveisLegais',
            field=models.ManyToManyField(default=None, related_name='segcadastro_pessoa_juridica_responsavel_legal', to='segCadastro.Responsavel', verbose_name=b'Respons\xc3\xa1veis Legais'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='Placa',
            field=models.CharField(max_length=7, unique=True),
        ),
    ]
