# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0009_auto_20160222_0312'),
    ]

    operations = [
        migrations.RenameField(
            model_name='autorizacao_funcionamento',
            old_name='Tipo',
            new_name='TipoAF',
        ),
        migrations.RenameField(
            model_name='equipamento_saude',
            old_name='Tipo',
            new_name='TipoEquip',
        ),
        migrations.RenameField(
            model_name='veiculo',
            old_name='Tipo',
            new_name='TipoVeiculo',
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='AdmAplicar',
            field=models.BooleanField(verbose_name=b'Administrar/aplicar medicamentos'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='AferirParam',
            field=models.BooleanField(verbose_name=b'Aferir par\xc3\xa2metros fisiol\xc3\xb3gicos e bioqu\xc3\xadmico'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Armazenar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='DispRemoto',
            field=models.BooleanField(verbose_name=b'Dispensar por meio remoto'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Dispensar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Distribuir',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Embalar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='EstETO',
            field=models.BooleanField(verbose_name=b'Esterelizar ETO'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='EstOutras',
            field=models.BooleanField(verbose_name=b'Esterelizar outras'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='EstRadiacaoIon',
            field=models.BooleanField(verbose_name=b'Esterelizar radia\xc3\xa7\xc3\xa3o ionizante'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Expedir',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Exportar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Extrair',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Fabricar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Fracionar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Fragmentar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='ImpUsoProprio',
            field=models.BooleanField(verbose_name=b'Importar para uso pr\xc3\xb3prio'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Importar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Irradiar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Manipular',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Perfurar',
            field=models.BooleanField(verbose_name=b'Perfurar l\xc3\xb3bulo auricular para coloca\xc3\xa7\xc3\xa3o de brinco'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='PrestarAten',
            field=models.BooleanField(verbose_name=b'Prestar aten\xc3\xa7\xc3\xa3o farmac\xc3\xaautica domiciliar'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Purificar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='RealEtapFab',
            field=models.BooleanField(verbose_name=b'Realizar etapas de fabrica\xc3\xa7\xc3\xa3o'),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Reprocessar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Sintetizar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Transformar',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='Transportar',
            field=models.BooleanField(),
        ),
    ]
