# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-07 05:20
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0010_auto_20160222_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
