# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0010_auto_20160421_1621'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='Assunto',
            field=models.CharField(choices=[('AUTORIZA\xc7\xc3O DE FUNCIONAMENTO (AGEVISA)', b'AUTORIZA\xc3\x87\xc3\x83O DE FUNCIONAMENTO (AGEVISA)'), ('RELAT\xd3RIO T\xc9CNICO DE INSPE\xc7\xc3O', b'RELAT\xc3\x93RIO T\xc3\x89CNICO DE INSPE\xc3\x87\xc3\x83O'), ('TERMO DE INSPE\xc7\xc3O', b'TERMO DE INSPE\xc3\x87\xc3\x83O'), ('AUTO DE INFRA\xc7\xc3O', b'AUTO DE INFRA\xc3\x87\xc3\x83O'), ('TERMO DE APREENS\xc3O', b'TERMO DE APREENS\xc3\x83O'), ('COMUNICADO DE DESINTERDI\xc7\xc3O', b'COMUNICADO DE DESINTERDI\xc3\x87\xc3\x83O'), ('TERMO DE INTERDI\xc7\xc3O CAUTELAR', b'TERMO DE INTERDI\xc3\x87\xc3\x83O CAUTELAR'), ('TERMO DE NOTIFICA\xc7\xc3O', b'TERMO DE NOTIFICA\xc3\x87\xc3\x83O'), (b'COMPROVANTE DE TAXA', b'COMPROVANTE DE TAXA'), ('ALVAR\xc1 DE LOCALIZA\xc7\xc3O DA PREFEITURA', b'ALVAR\xc3\x81 DE LOCALIZA\xc3\x87\xc3\x83O DA PREFEITURA'), (b'PLANTA BAIXA', b'PLANTA BAIXA'), (b'MEMORIAL DESCRITIVO', b'MEMORIAL DESCRITIVO'), ('CERTID\xc3O DE REGULARIDADE T\xc9CNICA', b'CERTID\xc3\x83O DE REGULARIDADE T\xc3\x89CNICA'), ('MANUAL DE BOAS PR\xc107206816003645ENTO DE RES\xcdDUOS', b'PLANO DE GERENCIAMENTO DE RES\xc3\x8dDUOS'), ('AUTORIZA\xc7\xc3O DE FUNCIONAMENTO (ANVISA)', b'AUTORIZA\xc3\x87\xc3\x83O DE FUNCIONAMENTO (ANVISA)'), (b'CONTRATO DE TRABALHO', b'CONTRATO DE TRABALHO'), ('STATUS DE TRANSMISS\xc3O (SNGPC)', b'STATUS DE TRANSMISS\xc3\x83O (SNGPC)'), (b'IDENTIDADE PROFISSIONAL DO CONSELHO DE CLASSE', b'IDENTIDADE PROFISSIONAL DO CONSELHO DE CLASSE'), ('ESCALA DE PLANT\xc3O DOS PROFISSIONAIS', b'ESCALA DE PLANT\xc3\x83O DOS PROFISSIONAIS'), ('DOCUMENTO DO VE\xcdCULO', b'DOCUMENTO DO VE\xc3\x8dCULO'), ('TREINAMENTO DOS FUNCION\xc1RIOS', b'TREINAMENTO DOS FUNCION\xc3\x81RIOS'), ('CONTRATO DE PRESTA\xc7\xc3O DE SERVI\xc7O', b'CONTRATO DE PRESTA\xc3\x87\xc3\x83O DE SERVI\xc3\x87O'), (b'RELA\xc3\x87\xc3\x83O DOS PROFISSIONAIS CONDUTORES', b'RELA\xc3\x87\xc3\x83O DOS PROFISSIONAIS CONDUTORES'), ('DOCUMENTO DE HABILITA\xc7\xc3O DE CONDUTOR', b'DOCUMENTO DE HABILITA\xc3\x87\xc3\x83O DE CONDUTOR'), ('CADASTRO NACIONAL DOS ESTABELECIMENTOS DE SA\xdaDE (CNES)', b'CADASTRO NACIONAL DOS ESTABELECIMENTOS DE SA\xc3\x9aDE (CNES)'), (b'COMPROVANTE DE PROCESSO', b'COMPROVANTE DE PROCESSO'), (b'OUTRO', b'OUTRO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='estabelecimento_desempenha_atv',
            name='ResponsavelTecnico',
            field=models.ManyToManyField(blank=True, related_name='resp_tecnico', to='segCadastro.Responsavel', verbose_name=b'Respons\xc3\xa1vel(eis) T\xc3\xa9cnico(s)'),
        ),
    ]
