# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 08:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0010_auto_20160222_0455'),
        ('segCadastro', '0005_auto_20160223_0009'),
    ]

    operations = [
    ]
