# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-25 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0011_auto_20160425_1611'),
    ]

    operations = [
        migrations.AddField(
            model_name='estabelecimento_desempenha_atv',
            name='TranspAli',
            field=models.BooleanField(default=False, verbose_name=b'Transportadora de Alimentos'),
        ),
        migrations.AddField(
            model_name='estabelecimento_desempenha_atv',
            name='TranspCorr',
            field=models.BooleanField(default=False, verbose_name=b'Transportadora de Correlatos'),
        ),
        migrations.AddField(
            model_name='estabelecimento_desempenha_atv',
            name='TranspCosm',
            field=models.BooleanField(default=False, verbose_name=b'Transportadora de Cosm\xc3\xa9ticos'),
        ),
        migrations.AddField(
            model_name='estabelecimento_desempenha_atv',
            name='TranspMed',
            field=models.BooleanField(default=False, verbose_name=b'Transportadora de Medicamentos'),
        ),
        migrations.AddField(
            model_name='estabelecimento_desempenha_atv',
            name='TranspSan',
            field=models.BooleanField(default=False, verbose_name=b'Transportadora de Saneantes'),
        ),
        migrations.AlterField(
            model_name='processo_tramita_setor',
            name='Situacao',
            field=models.CharField(blank=True, choices=[(b'ANA', b'EM AN\xc3\x81LISE'), (b'PEN_DOC_INC', b'PENDENTE - DOCUMENTA\xc3\x87\xc3\x83O INCOMPLETA'), (b'PEN_AGU_INSP', b'PENDENTE - AGUARDANDO INSPE\xc3\x87\xc3\x83O'), (b'PEN_AGU_CUMP_EXI', b'PENDENTE - AGUARDANDO CUMPRIMENTO DE EXIG\xc3\x8aNCIAS'), (b'DEF', b'DEFERIDO'), (b'IND', b'INDEFERIDO'), (b'ARQ', b'ARQUIVADO'), (b'OUT', b'OUTROS')], max_length=20),
        ),
    ]
