# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-15 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0012_auto_20160525_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa_juridica',
            name='CNPJ',
            field=models.CharField(default=None, max_length=14, unique=True),
        ),
    ]
