# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-21 06:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0011_merge'),
        ('segCadastro', '0013_auto_20160319_1423'),
    ]

    operations = [
    ]
