# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-20 04:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('segCadastro', '0015_auto_20160920_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa_juridica',
            name='CNPJ',
            field=models.CharField(blank=True, default=None, max_length=14, null=True, unique=True),
        ),
    ]
